server:
  port: 8399

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: jaebin
      password: jbchoi
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName=org: org.h2.Driver
    username: sa
    password:
  jpa:
    database-flatform: org.hibernate.dialect.H2Dialect
    showsql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

